# ============== Project Configuration ==============
dataset:
  path: final comments data.csv
  text_columns: [comment_text, comment, text, content, body, message]
  label_columns: [label, reward, target, class]
  use_weak_labels_if_no_label: true
  weak_label_from: Sum of num_likes
  weak_label_threshold: auto_median
  zero_shot_if_no_label: false
  positive_label_name: rewardable
  negative_label_name: unrewardable

training:
  model_name: distilbert-base-uncased
  max_length: 128
  batch_size: 16
  epochs: 3
  learning_rate: 2e-5
  output_dir: ./semantic_model
  seed: 42
  eval_split: 0.2

zero_shot:
  model_name: facebook/bart-large-mnli
  candidate_labels: [rewardable, unrewardable]
  hypothesis_template: "This comment is {}."

  